<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * This is the model class for table "fahrzeug_vehicle".
 *
 * @property int $nr_inside_id
 * @property string $fin_vehicle_number
 * @property string $alte_nr_old_insite_number
 * @property string $modell_car_model
 * @property string $herstellungsjahr_manufacturing_jear
 * @property string $verkaufsstatus_sale_state
 * @property string $bilder_images
 * @property string $sonstiges_other
 */
class FahrzeugVehicle extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'fahrzeug_vehicle';
    }
     /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nr_inside_id', 'fin_vehicle_number', 'modell_car_model',
                'herstellungsjahr_manufacturing_jear', 'verkaufsstatus_sale_state', 'bilder_images'], 'required'],
            [['nr_inside_id'], 'integer'],
            [['modell_car_model', 'verkaufsstatus_sale_state', 'bilder_images', 'sonstiges_other'], 'string'],
            [['herstellungsjahr_manufacturing_jear'], 'safe'],
            [['fin_vehicle_number', 'alte_nr_old_insite_number'], 'string', 'max' => 15],
            [['fin_vehicle_number'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'nr_inside_id' => 'Nr (Inside ID)',
            'fin_vehicle_number' => 'Fin (Vehicle Number)',
            'alte_nr_old_insite_number' => 'Alte Nr (Old Inside Number)',
            'modell_car_model' => 'Modell (Car Model)',
            'herstellungsjahr_manufacturing_jear' => 'Herstellungsjahr (Manufacturing Jear)',
            'verkaufsstatus_sale_state' => 'Verkaufsstatus (Sale State)',
            'bilder_images' => 'Bilder (Images)',
            'sonstiges_other' => 'Sonstiges (Other)',
        ];
    }
    public function beforeSave($insert)
    {
        //var_dump($insert);Exit();

        if($this->isNewRecord && !(FzgBestand::findOne($this->nr_inside_id))) {
            $fzg_b = new FzgBestand();
            $fzg_b->id = $this->nr_inside_id;
            $fzg_b->modell = $this->modell_car_model;
            $fzg_b->fin = $this->fin_vehicle_number;
            $fzg_b->nr = $this->alte_nr_old_insite_number;
            $fzg_b->vk_status = $this->verkaufsstatus_sale_state;
            /*$fzg_b->ek_datum = null;
            $fzg_b->verkaeufer = null;
            $fzg_b->ek_netto_preis = null;
            $fzg_b->ek_mwst = null;
            $fzg_b->ek_brutto_preis = null;
            $fzg_b->vk_datum = null;
            $fzg_b->kaeufer = null;
            $fzg_b->vk_netto_preis = null;
            $fzg_b->vk_mwst = null;
            $fzg_b->vk_brutto_preis = null;
            $fzg_b->gewinn = null;
            $fzg_b->mitarbeiter_employee = null;
            $fzg_b->sonstiges = null;*/
            $fzg_b->save();
            // var_dump($fzg_b->getErrors());Exit();
        }
        else if(($fzg_b = FzgBestand::findOne($this->nr_inside_id)) != null){
            if( !($fzg_b->fin)){
                $fzg_b->fin = $this->fin_vehicle_number;
            }
            $fzg_b->id = $this->nr_inside_id;
            $fzg_b->modell = $this->modell_car_model;
            $fzg_b->vk_status = $this->verkaufsstatus_sale_state;
            $fzg_b->nr = $this->alte_nr_old_insite_number;
            /*$fzg_b->ek_datum = null;
            $fzg_b->verkaeufer = null;
            $fzg_b->ek_netto_preis = null;
            $fzg_b->ek_mwst = null;
            $fzg_b->ek_brutto_preis = null;
            $fzg_b->vk_datum = null;
            $fzg_b->kaeufer = null;
            $fzg_b->vk_netto_preis = null;
            $fzg_b->vk_mwst = null;
            $fzg_b->vk_brutto_preis = null;
            $fzg_b->gewinn = null;
            $fzg_b->mitarbeiter_employee = null;
            $fzg_b->sonstiges = null;*/
            $fzg_b->save();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}



